# Generated by Django 4.2.2 on 2023-06-26 01:56

import Museum.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/category/', validators=[Museum.models.validate_image_size])),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='media/event/', validators=[Museum.models.validate_image_size])),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/exhibit_images/')),
                ('description', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='media/exhibit_audio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Museum.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Экспонаты',
            },
        ),
    ]
